// Code generated by Thrift Compiler (0.22.0). DO NOT EDIT.

package parquet

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"iter"
	"log/slog"
	"regexp"
	"strings"
	"time"

	thrift "github.com/apache/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var (
	_ = bytes.Equal
	_ = context.Background
	_ = errors.New
	_ = fmt.Printf
	_ = iter.Pull[int]
	_ = slog.Log
	_ = time.Now
	_ = thrift.ZERO
	// (needed by validator.)
	_ = strings.Contains
	_ = regexp.MatchString
)

func init() {
}
